file = open("demo",'w')
file.write("Adding some random content into the file")
file.close()
file = open("demo",'r')
content= file.read()
print(content)
file = open("demo",'a')
file.write("Adding some additional content")
file.close()
file = open("demo",'r')
newcontent = file.read()
print(newcontent)
file.close()

